// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLmM_Jk6Jmdsy5FENgQPM5DLJGO8Qouk',
    appId: '1:871300221872:web:9cae3b30d91414e4592475',
    messagingSenderId: '871300221872',
    projectId: 'graduation-5e09a',
    authDomain: 'graduation-5e09a.firebaseapp.com',
    storageBucket: 'graduation-5e09a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDv4ndPrwKVX6jfpKeYEaxRoEW41CF6s',
    appId: '1:871300221872:android:3c410188f0750c92592475',
    messagingSenderId: '871300221872',
    projectId: 'graduation-5e09a',
    storageBucket: 'graduation-5e09a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR6hwJElZYc5PBwl98GEscrpPC9SvwpSM',
    appId: '1:871300221872:ios:d0d9a2cb1801392b592475',
    messagingSenderId: '871300221872',
    projectId: 'graduation-5e09a',
    storageBucket: 'graduation-5e09a.appspot.com',
    iosClientId: '871300221872-7oetncos86db45l9iprmeaf8hc9hpuhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR6hwJElZYc5PBwl98GEscrpPC9SvwpSM',
    appId: '1:871300221872:ios:d0d9a2cb1801392b592475',
    messagingSenderId: '871300221872',
    projectId: 'graduation-5e09a',
    storageBucket: 'graduation-5e09a.appspot.com',
    iosClientId: '871300221872-7oetncos86db45l9iprmeaf8hc9hpuhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduation',
  );
}
